version: '3.4'

services:
  terraform:
    container_name: terraform
    working_dir: /infra-as-code
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.terraform
    volumes:
      - "./terraform:/infra-as-code"
      - "./scripts/plan-and-apply.sh:/scripts/plan-and-apply.sh"
    command: bash "../scripts/plan-and-apply.sh"

  pulumi:
    container_name: pulumi
    working_dir: /infra-as-code
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.terraform
    volumes:
      - "./pulumi/PulumiSample:/infra-as-code"
    command: "pulumi up --yes --stack PulumiSample --non-interactive"